// demos/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { filter, map } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  showDgDemos = true;
  activeRoute = '';

  constructor(private router: Router) {}

  ngAfterViewInit() {
    this.router.events.subscribe(value => (this.activeRoute = this.router.url.toString()));
  }

  handleGroupExpand(event: Event) {
    this.showDgDemos = !this.showDgDemos;
  }
}

<main id="demo-app" cds-layout="vertical align:horizontal-stretch">
  <header id="app-header" cds-layout="horizontal align:vertical-center gap:md p-l:sm p-l@md:md">
    <cds-icon shape="clarity-logo" size="lg"></cds-icon>
    Clarity Angular Demos
  </header>
  <div cds-layout="horizontal wrap:none align:vertical-stretch">
    <div id="app-sidenav" cds-layout="horizontal wrap:none align:stretch">
      <cds-navigation [attr.expanded]="true">
        <cds-navigation-group [expanded]="showDgDemos" (expandedChange)="handleGroupExpand($event)">
          <cds-navigation-start>Datagrid</cds-navigation-start>
          <cds-navigation-item [active]="'/datagrid/basic' === activeRoute || '/datagrid' === activeRoute">
            <a routerLink="/datagrid/basic">Basic</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/detail' === activeRoute">
            <a routerLink="/datagrid/detail">Detail</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/filtering' === activeRoute">
            <a routerLink="/datagrid/filtering">Filtering</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/full-async' === activeRoute">
            <a routerLink="/datagrid/full-async">Full async</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/hide-show-column' === activeRoute">
            <a routerLink="/datagrid/hide-show-column">Hide/show columns</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/multi-action' === activeRoute">
            <a routerLink="/datagrid/multi-action">Multi action</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/multi-select' === activeRoute">
            <a routerLink="/datagrid/multi-select">Mulit select</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/pagination' === activeRoute">
            <a routerLink="/datagrid/pagination">Pagination</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/pin-columns' === activeRoute">
            <a routerLink="/datagrid/pin-columns">Pin columns</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/single-action' === activeRoute">
            <a routerLink="/datagrid/single-action">Single action</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/single-select' === activeRoute">
            <a routerLink="/datagrid/single-select">Single select</a>
          </cds-navigation-item>
          <cds-navigation-item [active]="'/datagrid/sorting' === activeRoute">
            <a routerLink="/datagrid/sorting">Sorting</a>
          </cds-navigation-item>
        </cds-navigation-group>
      </cds-navigation>
      <cds-divider orientation="vertical"></cds-divider>
    </div>
    <div class="app-content" cds-layout="p-x:md">
      <router-outlet></router-outlet>
    </div>
  </div>
</main>

// demos/react/src/App.tsx
import { BrowserRouter as Router, Switch, Route, Link } from 'react-router-dom';
import logo from './logo.svg';
import './App.scss';

import { CdsNavigation, CdsNavigationItem } from '@cds/react/navigation';
import { CdsAlert, CdsAlertGroup } from '@cds/react/alert';
import { CdsDivider } from '@cds/react/divider';

import Basic from './components/grid/basic';
import RowMultiSelect from './components/grid/row-multi-select';
import RowSingleSelect from './components/grid/row-single-select';
import RowSingleAction from './components/grid/row-single-action';
import RowMultiAction from './components/grid/row-multi-action';
import Pagination from './components/grid/pagination';
import Filtering from './components/grid/filtering';
import Sorting from './components/grid/sorting';
import PinColumns from './components/grid/pin-columns';
import Detail from './components/grid/detail';
import HideShowColumns from './components/grid/hide-show-columns';
import AsyncData from './components/grid/async-data';
import FullDemo from './components/grid/full';
import AsyncDataFull from './components/grid/async-data-full';

function App() {
  return (
    <main>
      <CdsAlertGroup type="banner" status="warning">
        <CdsAlert>
          This component or utility is offered as a preview. This means we are currently working on it and seeking
          feedback. Please be aware that this component or utility may have breaking changes before we finish working on
          it.
        </CdsAlert>
      </CdsAlertGroup>
      <header className="demo-header" cds-layout="horizontal gap:md align:vertical-center p:md" cds-text="body">
        <img src={logo} alt="logo" />
        <span>Core React Demos</span>
      </header>

      <Router>
        <div className="router-container">
          <CdsNavigation expanded>
            <CdsNavigationItem>
              <Link to="/">Basic</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/filtering">Filtering</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/sorting">Sorting</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/row-single-select">Row Single Select</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/row-multi-select">Row Multi Select</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/row-single-action">Row Single Action</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/row-multi-action">Row Multi Action</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/pagination">Pagination</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/pin-columns">Pin Columns</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/detail">Detail</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/hide-show-columns">Hide/Show Columns</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/async-data">Async Data</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/full-demo">Full Demo</Link>
            </CdsNavigationItem>
            <CdsNavigationItem>
              <Link to="/async-data-full-demo">Async Data - Full Demo</Link>
            </CdsNavigationItem>
          </CdsNavigation>
          <CdsDivider orientation="vertical"></CdsDivider>
          <div cds-layout="align:stretch p-x:md" cds-text="body">
            {/* A <Switch> looks through its children <Route>s and
            renders the first one that matches the current URL. */}
            <Switch>
              <Route path="/filtering">
                <Filtering />
              </Route>
              <Route path="/sorting">
                <Sorting />
              </Route>
              <Route path="/row-single-select">
                <RowSingleSelect />
              </Route>
              <Route path="/row-multi-select">
                <RowMultiSelect />
              </Route>
              <Route path="/row-single-action">
                <RowSingleAction />
              </Route>
              <Route path="/row-multi-action">
                <RowMultiAction />
              </Route>
              <Route path="/pagination">
                <Pagination />
              </Route>
              <Route path="/pin-columns">
                <PinColumns />
              </Route>
              <Route path="/detail">
                <Detail />
              </Route>
              <Route path="/hide-show-columns">
                <HideShowColumns />
              </Route>
              <Route path="/async-data">
                <AsyncData />
              </Route>
              <Route path="/full-demo">
                <FullDemo />
              </Route>
              <Route path="/async-data-full-demo">
                <AsyncDataFull />
              </Route>
              <Route path="/">
                <Basic />
              </Route>
            </Switch>
          </div>
        </div>
      </Router>
    </main>
  );
}

export default App;
